### ISSUE TITLE
Starting nodes from QT causes seg fault

### ISSUE THREAD

**Issue by defunctec** [Crowndev/crown#134]
**Description**
When starting Masternodes from GUI in Ubuntu, the wallet crashes with no debug report.
Core dump seg fault is shown.

**Expected behaviour**
Client should stay active and start the node

**To reproduce**
Try to start a node from the GUI

**System information**
GUI
Linux Ubuntu 22.04

**Comment by defunctec** [comment]
Starting MN/SN from console within the QT works.

**Comment by walkjivefly** [comment]
gdb says
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000557b7021bb1c in WalletModel::getEncryptionStatus() const ()
[Current thread is 1 (Thread 0x7f59e82f8c80 (LWP 11876))]
(gdb) bt
#0  0x0000557b7021bb1c in WalletModel::getEncryptionStatus() const ()
#1  0x0000557b702970f9 in MasternodeList::on_startButton_clicked() ()
#2  0x0000557b702b8605 in MasternodeList::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#3  0x0000557b70fc769e in QMetaObject::activate(QObject*, int, int, void**) ()
#4  0x0000557b710dac0b in QAction::activate(QAction::ActionEvent) ()
#5  0x0000557b711d6392 in QMenuPrivate::activateCausedStack(QVector<QPointer<QWidget> > const&, QAction*, QAction::ActionEvent, bool) ()
#6  0x0000557b711de6e0 in QMenuPrivate::activateAction(QAction*, QAction::ActionEvent, bool) ()
#7  0x0000557b711df5db in QMenu::mouseReleaseEvent(QMouseEvent*) ()
#8  0x0000557b71114418 in QWidget::event(QEvent*) ()
#9  0x0000557b711e194b in QMenu::event(QEvent*) ()
#10 0x0000557b710dec91 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#11 0x0000557b710e6d28 in QApplication::notify(QObject*, QEvent*) ()
#12 0x0000557b70f9af10 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
#13 0x0000557b710e5dcb in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
#14 0x0000557b7112c91f in QWidgetWindow::handleMouseEvent(QMouseEvent*) ()
#15 0x0000557b7112ef65 in QWidgetWindow::event(QEvent*) ()
#16 0x0000557b710dec91 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#17 0x0000557b710e6910 in QApplication::notify(QObject*, QEvent*) ()
#18 0x0000557b70f9af10 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
#19 0x0000557b70a6435b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
#20 0x0000557b70a6564d in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
#21 0x0000557b70a3f9ac in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#22 0x0000557b709dcb53 in QXcbUnixEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#23 0x0000557b70f994ef in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#24 0x0000557b711dc53d in QMenu::exec(QPoint const&, QAction*) ()
#25 0x0000557b70292f78 in MasternodeList::showContextMenu(QPoint const&) ()
#26 0x0000557b702b85f9 in MasternodeList::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#27 0x0000557b70fc769e in QMetaObject::activate(QObject*, int, int, void**) ()
#28 0x0000557b711151ee in QWidget::event(QEvent*) ()
#29 0x0000557b71182e6e in QFrame::event(QEvent*) ()
#30 0x0000557b71297352 in QAbstractItemView::viewportEvent(QEvent*) ()
#31 0x0000557b70f99a2b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) [clone .part.112] ()
#32 0x0000557b710dec81 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
--Type <RET> for more, q to quit, c to continue without paging--
   ()
#33 0x0000557b710e78b0 in QApplication::notify(QObject*, QEvent*) ()
#34 0x0000557b70f9aa20 in QCoreApplication::forwardEvent(QObject*, QEvent*, QEvent*) ()
#35 0x0000557b7112c5d4 in QWidgetWindow::handleMouseEvent(QMouseEvent*) ()
#36 0x0000557b7112ef65 in QWidgetWindow::event(QEvent*) ()
#37 0x0000557b710dec91 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#38 0x0000557b710e6910 in QApplication::notify(QObject*, QEvent*) ()
#39 0x0000557b70f9af10 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
#40 0x0000557b70a6435b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
#41 0x0000557b70a6564d in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
#42 0x0000557b70a3f9ac in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#43 0x0000557b709dcb53 in QXcbUnixEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#44 0x0000557b70f994ef in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#45 0x0000557b70fa2c56 in QCoreApplication::exec() ()
#46 0x0000557b70194d85 in GuiMain(int, char**) ()
#47 0x00007f59e8c2909b in __libc_start_main ()
   from /lib/x86_64-linux-gnu/libc.so.6
#48 0x0000557b7018ed9a in _start ()
```

**Comment by BlockMechanic** [comment]
disabled GUI convineince, lets put on list

**Comment by walkjivefly** [comment]
Again with the making life harder for non-technical users. Again, that'll do wonders for the number who bother to create nodes and keep them running.
