### ISSUE TITLE
v0.0.0.62 QT wallet segfault on voting

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#141]
QT wallet segfaults when attempting to vote on a proposal

**Expected behavior**
Voting should complete OK without crashing

**Actual behavior**
QT wallet segfaults when attempting to vote

**To reproduce**
Fire up QT wallet, unlock wallet, go to MN page, voting tab, try to vote

**System information**
v0.0.0.62 self compiled on MX-19 Linux (because team built version won't run on anything earlier than Ubuntu 20/22)

gdb shows
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055ecfa80cb1c in WalletModel::getEncryptionStatus() const ()
[Current thread is 1 (Thread 0x7f2b4f9a3c80 (LWP 15276))]
(gdb) bt
#0  0x000055ecfa80cb1c in WalletModel::getEncryptionStatus() const ()
#1  0x000055ecfa88a4db in MasternodeList::on_voteManyYesButton_clicked() ()
#2  0x000055ecfa8a9655 in MasternodeList::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#3  0x000055ecfa8a97d3 in MasternodeList::qt_metacall(QMetaObject::Call, int, void**) ()
#4  0x000055ecfb5b875c in QMetaObject::activate(QObject*, int, int, void**) ()
#5  0x000055ecfb7776d3 in QAbstractButtonPrivate::emitClicked() ()
#6  0x000055ecfb778b5f in QAbstractButtonPrivate::click() ()
#7  0x000055ecfb778d10 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
#8  0x000055ecfb705418 in QWidget::event(QEvent*) ()
#9  0x000055ecfb6cfc91 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#10 0x000055ecfb6d7d28 in QApplication::notify(QObject*, QEvent*) ()
#11 0x000055ecfb58bf10 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
#12 0x000055ecfb6d6dcb in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
#13 0x000055ecfb71d00c in QWidgetWindow::handleMouseEvent(QMouseEvent*) ()
#14 0x000055ecfb71ff65 in QWidgetWindow::event(QEvent*) ()
#15 0x000055ecfb6cfc91 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#16 0x000055ecfb6d7910 in QApplication::notify(QObject*, QEvent*) ()
#17 0x000055ecfb58bf10 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
#18 0x000055ecfb05535b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
#19 0x000055ecfb05664d in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
#20 0x000055ecfb0309ac in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#21 0x000055ecfafcdb53 in QXcbUnixEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#22 0x000055ecfb58a4ef in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#23 0x000055ecfb593c56 in QCoreApplication::exec() ()
#24 0x000055ecfa785d85 in GuiMain(int, char**) ()
#25 0x00007f2b502d409b in __libc_start_main ()
   from /lib/x86_64-linux-gnu/libc.so.6
#26 0x000055ecfa77fd9a in _start ()
```

which is very similar to the backtrace in https://github.com/Crowndev/crown/issues/134 so fixing either will probably fix both issues

**Comment by BlockMechanic** [comment]
Let's put thi son the list of GUI nice to fix.

**Comment by walkjivefly** [comment]
yeah, why not, that'll do wonders for the number of people who vote on proposals.

**Comment by BlockMechanic** [comment]
Can we possibly do a survey on how many active users we have, and of those how many use the QT ?
