### ISSUE TITLE
v0.0.0.69 GUI asset creation core dumps

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#191]
Asset creation core dumps. 

debug.log shows:
```
2022-11-06T16:29:35Z GUI: Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.
```

gdb core shows:
```
Core was generated by `crown-qt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005634b10ee778 in QEventLoop::exit(int) ()
[Current thread is 1 (Thread 0x7f3beb8b8800 (LWP 7580))]
(gdb) bt
#0  0x00005634b10ee778 in QEventLoop::exit(int) ()
#1  0x00005634b1537982 in QDialog::setVisible(bool) ()
#2  0x00005634b15352e1 in QDialog::~QDialog() ()
#3  0x00005634b0227571 in AssetManagerPage::on_CreateNewAsset_clicked() [clone .cold] ()
#4  0x00005634b03e3bbe in AssetManagerPage::qt_metacall(QMetaObject::Call, int, void**) ()
#5  0x00005634b111bef8 in void doActivate<false>(QObject*, int, void**) ()
#6  0x00005634b145cb45 in QAbstractButtonPrivate::emitClicked() ()
#7  0x00005634b145e8db in QAbstractButtonPrivate::click() ()
#8  0x00005634b145eaf7 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
#9  0x00005634b13ddb38 in QWidget::event(QEvent*) ()
#10 0x00005634b13a4ec3 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#11 0x00005634b13ad862 in QApplication::notify(QObject*, QEvent*) ()
#12 0x00005634b10f0c18 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
#13 0x00005634b13ac246 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
#14 0x00005634b13f6d05 in QWidgetWindow::handleMouseEvent(QMouseEvent*) ()
#15 0x00005634b13f9f45 in QWidgetWindow::event(QEvent*) ()
#16 0x00005634b13a4ec3 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#17 0x00005634b10f0c18 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
#18 0x00005634b0bae04f in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
#19 0x00005634b0e3842c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#20 0x00005634b1293527 in QXcbUnixEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#21 0x00005634b10eee16 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#22 0x00005634b10f8318 in QCoreApplication::exec() ()
#23 0x00005634b0338afa in GuiMain(int, char**) ()
#24 0x00007f3beb9e8d90 in __libc_start_call_main (
    main=main@entry=0x5634b031a420 <main>, argc=argc@entry=1, 
    argv=argv@entry=0x7ffe709ff1e8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#25 0x00007f3beb9e8e40 in __libc_start_main_impl (main=0x5634b031a420 <main>, 
    argc=1, argv=0x7ffe709ff1e8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffe709ff1d8)
    at ../csu/libc-start.c:392
#26 0x00005634b0332505 in _start ()

 _start ()
(gdb) info threads
  Id   Target Id                        Frame 
* 1    Thread 0x7f3beb8b8800 (LWP 7580) 0x00005634b10ee778 in QEventLoop::exit(int) ()
  2    Thread 0x7f3bdbda1640 (LWP 7585) 0x00007f3bebad7e7e in __ppoll (
    fds=0x7f3bce3654b8, nfds=1, timeout=<optimized out>, sigmask=0x0)
    at ../sysdeps/unix/sysv/linux/ppoll.c:42
  3    Thread 0x7f3bcb7fe640 (LWP 7589) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, 
    futex_word=0x7f3bcc052820) at ./nptl/futex-internal.c:57
  4    Thread 0x7f3be98d6640 (LWP 7611) 0x00007f3bebae4fde in epoll_wait (
    epfd=7, events=0x7f3b9ff50700, maxevents=32, timeout=1477891)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  5    Thread 0x7f3ba93a2640 (LWP 7615) __futex_abstimed_wait_common64 (
    private=-1302487144, cancel=true, abstime=0x7f3ba93a1b00, op=137, 
    expected=0, futex_word=0x7f3bcc161470) at ./nptl/futex-internal.c:57
  6    Thread 0x7f3ba2df2640 (LWP 7619) 0x00007f3bebad7e7e in __ppoll (
    fds=0x7f3bb4001038, nfds=1, timeout=<optimized out>, sigmask=0x0)
    at ../sysdeps/unix/sysv/linux/ppoll.c:42
  7    Thread 0x7f3ba13b8640 (LWP 7758) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x7f3ba13b7c70, op=137, expected=0, 
    futex_word=0x5634b387d924) at ./nptl/futex-internal.c:57
  8    Thread 0x7f3ba0bb7640 (LWP 7759) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x7f3ba0bb6c70, op=137, expected=0, 
    futex_word=0x5634b387db50) at ./nptl/futex-internal.c:57
  9    Thread 0x7f3ba35f3640 (LWP 7618) 0x00007f3bebad7e7e in __ppoll (
    fds=0x7f3bac001438, nfds=1, timeout=<optimized out>, sigmask=0x0)
    at ../sysdeps/unix/sysv/linux/ppoll.c:42
  10   Thread 0x7f3bd8d07640 (LWP 7587) __futex_abstimed_wait_common64 (
    private=-463905024, cancel=true, abstime=0x7f3bd8d06c40, op=393, 
    expected=0, futex_word=0x7f3bcc001978) at ./nptl/futex-internal.c:57
  11   Thread 0x7f3bea8d9640 (LWP 7581) 0x00007f3bebad7d7f in __GI___poll (
    fds=0x7f3bea8d8c08, nfds=1, timeout=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
  12   Thread 0x7f3ba8ba1640 (LWP 7616) __futex_abstimed_wait_common64 (
    private=1797285236, cancel=true, abstime=0x7f3ba8ba04f0, op=137, 
    expected=0, futex_word=0x7f3bcc161470) at ./nptl/futex-internal.c:57
  13   Thread 0x7f3be88d4640 (LWP 7584) 0x00007f3bebad7e7e in __ppoll (
    fds=0x7f3bd40188e8, nfds=6, timeout=<optimized out>, sigmask=0x0)
    at ../sysdeps/unix/sysv/linux/ppoll.c:42
  14   Thread 0x7f3bd9508640 (LWP 7586) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, 
    futex_word=0x5634b25d7c54 <scriptcheckqueue+84>)
    at ./nptl/futex-internal.c:57
  15   Thread 0x7f3bcbfff640 (LWP 7588) 0x00007f3bebae4fde in epoll_wait (
    epfd=20, events=0x7f3bcc06fdd0, maxevents=32, timeout=-1)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  16   Thread 0x7f3bcaffd640 (LWP 7590) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, 
    futex_word=0x7f3bcc052820) at ./nptl/futex-internal.c:57
--Type <RET> for more, q to quit, c to continue without paging--
  17   Thread 0x7f3ba3fff640 (LWP 7617) __futex_abstimed_wait_common64 (
    private=-1543509416, cancel=true, abstime=0x7f3ba3ffec40, op=137, 
    expected=0, futex_word=0x7f3bcc161414) at ./nptl/futex-internal.c:57
  18   Thread 0x7f3ba9ba3640 (LWP 7614) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, 
    futex_word=0x7f3b9ff4abd8) at ./nptl/futex-internal.c:57
  19   Thread 0x7f3bc97fa640 (LWP 7594) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, 
    futex_word=0x5634b25e19fc <leveldb::Env::Default()::env_container+92>)
    at ./nptl/futex-internal.c:57
  20   Thread 0x7f3bc9ffb640 (LWP 7592) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, 
    futex_word=0x7f3bcc052820) at ./nptl/futex-internal.c:57
  21   Thread 0x7f3baaba5640 (LWP 7612) 0x00007f3bebad7d7f in __GI___poll (
    fds=0x7f3b984be6c0, nfds=11, timeout=50)
    at ../sysdeps/unix/sysv/linux/poll.c:29
  22   Thread 0x7f3ba25f1640 (LWP 7621) 0x00007f3bebad7e7e in __ppoll (
    fds=0x7f3bbc001068, nfds=1, timeout=<optimized out>, sigmask=0x0)
    at ../sysdeps/unix/sysv/linux/ppoll.c:42
  23   Thread 0x7f3bca7fc640 (LWP 7591) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, 
    futex_word=0x7f3bcc052820) at ./nptl/futex-internal.c:57
```

**Comment by BlockMechanic** [comment]
There was a clash between two separate mechanisms, one for creation outright and one for detection. Should be resolved  in next version

**Comment by walkjivefly** [comment]
Confirmed GUI asset creation works in v0.0.0.75
