### ISSUE TITLE
v0.0.0.69 EXCEPTION: St13runtime_error in crownd

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#194]
Possibly the result of running on an abused VPS, but crownd (MN) fell over with debug.log saying
```
2022-11-08T11:44:28Z CreateCoinStake: Found valid kernel for mn/sn collateral COutPoint(0781ca62c7931f913ca764990cc7b578f4b60003b7abf07670e4845259dbac0d, 1)
2022-11-08T11:44:28Z CreateCoinStake: OutPoint: 2ff84ecf57fe3b38aa08933cfa0e844b98e1ffce1ba9cf09712268783604b204:1 Modifier=e9d671c32dee1980eff6015528402387cf97d6393c1ad4c356aca4a3a0e6ec1e timeblockfrom=1667891742 time=1667904808 amount=1000000000000
2022-11-08T11:44:28Z CreateNewBlock: vtx size 2
2022-11-08T11:44:28Z CreateNewBlock(): block weight: 4000 txs: 0 fees: 0 sigops 400
2022-11-08T11:44:28Z ERROR: TestBlockValidity: Consensus::ContextualCheckBlockHeader: time-too-old, block's timestamp is too early
2022-11-08T11:44:28Z

************************
EXCEPTION: St13runtime_error
CreateNewBlock: TestBlockValidity failed: time-too-old, block's timestamp is too early
CBlock(hash=e0c2f620068815236c0b5e1c56a13500b40c75ec172b53b6058485e32aa1e8a1, ver=0x00000200, hashPrevBlock=640c0a54b15dafc2f7ec1193e1a445dbcd073034668e272bc3f4d0c88e8bcd04, hashMerkleRoot=1437c9201147d3d2c0efb01c9ae957518e8239a9f4075017581c92805dcf775c, nTime=1667904808, nBits=1a065533, nNonce=0, vtx=2)
  CTransaction(hash=d0545662d2, ver=4, type=0, nTime=1667907832, vin.size=1, vout.size=3, nLockTime=0, extraPayload.size=0)
CTxIn(COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295), coinbase 02447000)
    CTxOutAsset
Name : Crown
Symbol : CRW
CAssetID : 1892dd304d6cf4e2f40d2bf465e8d47a48c240d375efac65f86a680c9706e401
Contract Hash : 0000000000000000000000000000000000000000000000000000000000000000
Details (ver=1, transferable=yes, convertable=yes, limited=no, restricted=no, stakable=yes, infatable=no, type=1, expiry=0)

(nValue=0.00000000, scriptPubKey=)

    CTxOutAsset
Name : Crown
Symbol : CRW
CAssetID : 1892dd304d6cf4e2f40d2bf465e8d47a48c240d375efac65f86a680c9706e401
Contract Hash : 0000000000000000000000000000000000000000000000000000000000000000
Details (ver=1, transferable=yes, convertable=yes, limited=no, restricted=no, stakable=yes, infatable=no, type=1, expiry=0)

(nValue=0.00000000, scriptPubKey=)

    CTxOutAsset
Name : Crown
Symbol : CRW
CAssetID : 1892dd304d6cf4e2f40d2bf465e8d47a48c240d375efac65f86a680c9706e401
Contract Hash : 0000000000000000000000000000000000000000000000000000000000000000
Details (ver=1, transferable=yes, convertable=yes, limited=no, restricted=no, stakable=yes, infatable=no, type=1, expiry=0)

(nValue=3.70000000, scriptPubKey=OP_DUP OP_HASH160 aa8dfe7a72c41ab0146f2fca5c57311f31bcc537 OP_EQUALVERIFY OP_CHECKSIG)

    CTxOutAsset
Name : Crown
Symbol : CRW
CAssetID : 1892dd304d6cf4e2f40d2bf465e8d47a48c240d375efac65f86a680c9706e401
Contract Hash : 0000000000000000000000000000000000000000000000000000000000000000
Details (ver=1, transferable=yes, convertable=yes, limited=no, restricted=no, stakable=yes, infatable=no, type=1, expiry=0)

(nValue=0.80000000, scriptPubKey=OP_DUP OP_HASH160 33f4e9a7b42e3b98e96126f7139676a9b66702e0 OP_EQUALVERIFY OP_CHECKSIG)


  CTransaction(hash=a4e6a2bd56, ver=4, type=0, nTime=1667907832, vin.size=1, vout.size=1, nLockTime=0, extraPayload.size=0)
CTxIn(COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295), coinbase c002447000)
    CTxOutAsset
Name : Crown
Symbol : CRW
CAssetID : 1892dd304d6cf4e2f40d2bf465e8d47a48c240d375efac65f86a680c9706e401
Contract Hash : 0000000000000000000000000000000000000000000000000000000000000000
Details (ver=1, transferable=yes, convertable=yes, limited=no, restricted=no, stakable=yes, infatable=no, type=1, expiry=0)

(nValue=3.00000000, scriptPubKey=OP_DUP OP_HASH160 57f333bf545751aa9b637ab956040e4e34d0bc22 OP_EQUALVERIFY OP_CHECKSIG)



crown in scheduler
```
gdb says 
```Core was generated by `crownd'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139777444181568)
    at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0x7f2078e87640 (LWP 68591))]
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139777444181568)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139777444181568)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139777444181568, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007f207bb03476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007f207bae97f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007f207be92bbe in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f207be9e24c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f207be9e2b7 in std::terminate() ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f207be9e56b in __cxa_rethrow ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00005592a95a31c8 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<AppInitMain(util::Ref const&, NodeContext&, interfaces::BlockAndHeaderTipInfo*)::{lambda()#2}> > >::_M_run() [clone .cold] ()
#10 0x00007f207becc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007f207bb55b43 in start_thread (arg=<optimized out>)
    at ./nptl/pthread_create.c:442
#12 0x00007f207bbe7a00 in clone3 ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

(gdb) info threads
  Id   Target Id                         Frame 
* 1    Thread 0x7f2078e87640 (LWP 68591) __pthread_kill_implementation (
    no_tid=0, signo=6, threadid=139777444181568) at ./nptl/pthread_kill.c:44
  2    Thread 0x7f207babc780 (LWP 68589) 0x00007f207bba6868 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7ffff1e8ef10, 
    rem=0x7ffff1e8ef10) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  3    Thread 0x7f2079688640 (LWP 68590) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, 
    futex_word=0x5592aa25e1b4 <scriptcheckqueue+84>)
    at ./nptl/futex-internal.c:57
  4    Thread 0x7f2072ffd640 (LWP 68594) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, 
    futex_word=0x5592abc04740) at ./nptl/futex-internal.c:57
  5    Thread 0x7f2073fff640 (LWP 68592) 0x00007f207bbe6fde in epoll_wait (
    epfd=5, events=0x5592abc08d30, maxevents=32, timeout=-1)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  6    Thread 0x7f20727fc640 (LWP 68595) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, 
    futex_word=0x5592abc04744) at ./nptl/futex-internal.c:57
  7    Thread 0x7f20737fe640 (LWP 68593) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, 
    futex_word=0x5592abc04744) at ./nptl/futex-internal.c:57
  8    Thread 0x7f2071ffb640 (LWP 68596) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, 
    futex_word=0x5592abc04744) at ./nptl/futex-internal.c:57
  9    Thread 0x7f20557fa640 (LWP 68604) __futex_abstimed_wait_common64 (
    private=1797285236, cancel=true, abstime=0x7f20557f9570, op=137, 
    expected=0, futex_word=0x5592abc6da00) at ./nptl/futex-internal.c:57
  10   Thread 0x7f2057fff640 (LWP 68599) 0x00007f207bbe6fde in epoll_wait (
    epfd=34, events=0x5592ad7a4040, maxevents=32, timeout=2100000)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  11   Thread 0x7f2054ff9640 (LWP 68605) 0x00007f207bb64f89 in _int_malloc (
    av=av@entry=0x7f2034000030, bytes=bytes@entry=1260)
    at ./malloc/malloc.c:4001
  12   Thread 0x7f20567fc640 (LWP 68602) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, 
    futex_word=0x5592ad7a2f7c) at ./nptl/futex-internal.c:57
  13   Thread 0x7f2055ffb640 (LWP 68603) __futex_abstimed_wait_common64 (
    private=-1440332040, cancel=true, abstime=0x7f2055ffab80, op=137, 
    expected=0, futex_word=0x5592abc6da00) at ./nptl/futex-internal.c:57
  14   Thread 0x7f2033fff640 (LWP 68738) __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, 
    futex_word=0x5592aa265238 <leveldb::Env::Default()::env_container+88>)
    at ./nptl/futex-internal.c:57
  15   Thread 0x7f20577fe640 (LWP 68600) futex_wait (private=0, expected=2, 
    futex_word=0x7f207bce1760 <tzset_lock>)
    at ../sysdeps/nptl/futex-internal.h:146
```

**Comment by walkjivefly** [comment]
No occurrences since. Probably fixed.
