### ISSUE TITLE
Cannot create asset from GUI

### ISSUE THREAD

**Issue by defunctec** [Crowndev/crown#230]
Debug shows
`GUI: std:exception in thread : 0x7f2dda09b800
`

**Comment by walkjivefly** [comment]
v0.0.0.78 linux QT crashed with SIGSEGV filling in the New Asset fields.
Navigating and completing info fields, didn't get as far as clicking Create.
gdb shows
```
Core was generated by `crown-qt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055f9d51defe7 in QSortFilterProxyModelPrivate::proxy_to_source(QModelIndex const&) const ()
[Current thread is 1 (Thread 0x7f717d778800 (LWP 252854))]
(gdb) bt
#0  0x000055f9d51defe7 in QSortFilterProxyModelPrivate::proxy_to_source(QModelIndex const&) const ()
#1  0x000055f9d51e1e99 in QSortFilterProxyModelPrivate::store_persistent_indexes() const ()
#2  0x000055f9d51e653b in QSortFilterProxyModelPrivate::_q_sourceLayoutAboutToBeChanged(QList<QPersistentModelIndex> const&, QAbstractItemModel::LayoutChangeHint) ()
#3  0x000055f9d523c9e5 in void doActivate<false>(QObject*, int, void**) ()
#4  0x000055f9d51b83aa in QAbstractItemModel::layoutAboutToBeChanged(QList<QPersistentModelIndex> const&, QAbstractItemModel::LayoutChangeHint) ()
#5  0x000055f9d451c0ab in ContractTableModel::update() ()
#6  0x000055f9d523c9b1 in void doActivate<false>(QObject*, int, void**) ()
#7  0x000055f9d450a22b in ClientModel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#8  0x000055f9d523825e in QObject::event(QEvent*) ()
#9  0x000055f9d54c5693 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#10 0x000055f9d4507fdd in CrownApplication::notify(QObject*, QEvent*) ()
#11 0x000055f9d5210aca in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    ()
#12 0x000055f9d5214a4b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
#13 0x000055f9d525d6e5 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#14 0x000055f9d53b3ce2 in QXcbUnixEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#15 0x000055f9d520f5e6 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#16 0x000055f9d56576d2 in QDialog::exec() ()
#17 0x000055f9d44ed4cd in AssetManagerPage::on_CreateNewAsset_clicked() ()
#18 0x000055f9d45159be in AssetManagerPage::qt_metacall(QMetaObject::Call, int, void**) ()
#19 0x000055f9d523c6c8 in void doActivate<false>(QObject*, int, void**) ()
#20 0x000055f9d557d315 in QAbstractButtonPrivate::emitClicked() ()
#21 0x000055f9d557f0ab in QAbstractButtonPrivate::click() ()
#22 0x000055f9d557f2c7 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
#23 0x000055f9d54fe308 in QWidget::event(QEvent*) ()
#24 0x000055f9d54c5693 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#25 0x000055f9d54ce032 in QApplication::notify(QObject*, QEvent*) ()
#26 0x000055f9d4507fdd in CrownApplication::notify(QObject*, QEvent*) ()
#27 0x000055f9d52113e8 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
#28 0x000055f9d54cca16 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
#29 0x000055f9d55174d5 in QWidgetWindow::handleMouseEvent(QMouseEvent*) ()
#30 0x000055f9d551a715 in QWidgetWindow::event(QEvent*) ()
#31 0x000055f9d54c5693 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#32 0x000055f9d4507fdd in CrownApplication::notify(QObject*, QEvent*) ()
#33 0x000055f9d52113e8 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
--Type <RET> for more, q to quit, c to continue without paging-- 
#34 0x000055f9d4cce85f in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
#35 0x000055f9d4f58c3c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#36 0x000055f9d53b3cf7 in QXcbUnixEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#37 0x000055f9d520f5e6 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#38 0x000055f9d5218ae8 in QCoreApplication::exec() ()
#39 0x000055f9d445377a in GuiMain(int, char**) ()
#40 0x00007f717d8a8d90 in __libc_start_call_main (
    main=main@entry=0x55f9d4434ef0 <main>, argc=argc@entry=1, 
    argv=argv@entry=0x7fff42b91008)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#41 0x00007f717d8a8e40 in __libc_start_main_impl (main=0x55f9d4434ef0 <main>, 
    argc=1, argv=0x7fff42b91008, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fff42b90ff8)
    at ../csu/libc-start.c:392
#42 0x000055f9d444d185 in _start ()
```
and debug.log shows nothing relevant.

**Comment by walkjivefly** [comment]
Had a second crash in 0.0.0.78 linux QT. Attempted to create an asset, got a bit further than last time but a few seconds after popping an (incorrect) error message, it SIGSEGV'd again.
![Screenshot_2022-11-28_18-11-23](https://user-images.githubusercontent.com/17745270/204339835-4d80ea56-8bed-4b21-ad7b-c7b5127e84e5.png)
40.1 x 100 = 4010 < 4000 so it should have worked. 
A few seconds later it crashed, gdb shows
```
Core was generated by `crown-qt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055a58f4fafe7 in QSortFilterProxyModelPrivate::proxy_to_source(QModelIndex const&) const ()
[Current thread is 1 (Thread 0x7fdf31f9c800 (LWP 253734))]
(gdb) bt
#0  0x000055a58f4fafe7 in QSortFilterProxyModelPrivate::proxy_to_source(QModelIndex const&) const ()
#1  0x000055a58f4fde99 in QSortFilterProxyModelPrivate::store_persistent_indexes() const ()
#2  0x000055a58f50253b in QSortFilterProxyModelPrivate::_q_sourceLayoutAboutToBeChanged(QList<QPersistentModelIndex> const&, QAbstractItemModel::LayoutChangeHint) ()
#3  0x000055a58f5589e5 in void doActivate<false>(QObject*, int, void**) ()
#4  0x000055a58f4d43aa in QAbstractItemModel::layoutAboutToBeChanged(QList<QPersistentModelIndex> const&, QAbstractItemModel::LayoutChangeHint) ()
#5  0x000055a58e8380ab in ContractTableModel::update() ()
#6  0x000055a58f5589b1 in void doActivate<false>(QObject*, int, void**) ()
#7  0x000055a58e82622b in ClientModel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#8  0x000055a58f55425e in QObject::event(QEvent*) ()
#9  0x000055a58f7e1693 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#10 0x000055a58e823fdd in CrownApplication::notify(QObject*, QEvent*) ()
#11 0x000055a58f52caca in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    ()
#12 0x000055a58f530a4b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
#13 0x000055a58f5796e5 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#14 0x000055a58f6cfce2 in QXcbUnixEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#15 0x000055a58f52b5e6 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#16 0x000055a58f9736d2 in QDialog::exec() ()
#17 0x000055a58e80d96a in NewAssetPage::on_Create_clicked() ()
#18 0x000055a58e831dcc in NewAssetPage::qt_metacall(QMetaObject::Call, int, void**) ()
#19 0x000055a58f5586c8 in void doActivate<false>(QObject*, int, void**) ()
#20 0x000055a58f899315 in QAbstractButtonPrivate::emitClicked() ()
#21 0x000055a58f89b0ab in QAbstractButtonPrivate::click() ()
#22 0x000055a58f89b2c7 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
#23 0x000055a58f81a308 in QWidget::event(QEvent*) ()
#24 0x000055a58f7e1693 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#25 0x000055a58f7ea032 in QApplication::notify(QObject*, QEvent*) ()
#26 0x000055a58e823fdd in CrownApplication::notify(QObject*, QEvent*) ()
#27 0x000055a58f52d3e8 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
#28 0x000055a58f7e8a16 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
#29 0x000055a58f8334d5 in QWidgetWindow::handleMouseEvent(QMouseEvent*) ()
#30 0x000055a58f836715 in QWidgetWindow::event(QEvent*) ()
#31 0x000055a58f7e1693 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#32 0x000055a58e823fdd in CrownApplication::notify(QObject*, QEvent*) ()
#33 0x000055a58f52d3e8 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
--Type <RET> for more, q to quit, c to continue without paging--
#34 0x000055a58efea85f in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
#35 0x000055a58f274c3c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#36 0x000055a58f6cfcf7 in QXcbUnixEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#37 0x000055a58f52b5e6 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#38 0x000055a58f9736d2 in QDialog::exec() ()
#39 0x000055a58e8094cd in AssetManagerPage::on_CreateNewAsset_clicked() ()
#40 0x000055a58e8319be in AssetManagerPage::qt_metacall(QMetaObject::Call, int, void**) ()
#41 0x000055a58f5586c8 in void doActivate<false>(QObject*, int, void**) ()
#42 0x000055a58f899315 in QAbstractButtonPrivate::emitClicked() ()
#43 0x000055a58f89b0ab in QAbstractButtonPrivate::click() ()
#44 0x000055a58f89b2c7 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
#45 0x000055a58f81a308 in QWidget::event(QEvent*) ()
#46 0x000055a58f7e1693 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#47 0x000055a58f7ea032 in QApplication::notify(QObject*, QEvent*) ()
#48 0x000055a58e823fdd in CrownApplication::notify(QObject*, QEvent*) ()
#49 0x000055a58f52d3e8 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
#50 0x000055a58f7e8a16 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
#51 0x000055a58f8334d5 in QWidgetWindow::handleMouseEvent(QMouseEvent*) ()
#52 0x000055a58f836715 in QWidgetWindow::event(QEvent*) ()
#53 0x000055a58f7e1693 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#54 0x000055a58e823fdd in CrownApplication::notify(QObject*, QEvent*) ()
#55 0x000055a58f52d3e8 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
#56 0x000055a58efea85f in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
#57 0x000055a58f274c3c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#58 0x000055a58f6cfcf7 in QXcbUnixEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#59 0x000055a58f52b5e6 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#60 0x000055a58f534ae8 in QCoreApplication::exec() ()
#61 0x000055a58e76f77a in GuiMain(int, char**) ()
#62 0x00007fdf320ccd90 in __libc_start_call_main (
    main=main@entry=0x55a58e750ef0 <main>, argc=argc@entry=1, 
    argv=argv@entry=0x7fff961b2ef8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#63 0x00007fdf320cce40 in __libc_start_main_impl (main=0x55a58e750ef0 <main>, 
    argc=1, argv=0x7fff961b2ef8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fff961b2ee8)
    at ../csu/libc-start.c:392
#64 0x000055a58e769185 in _start ()
```
tail of debug.log shows nothing especially suspicious and ends with
```
...
2022-11-28T17:11:29Z sending getblocks (805 bytes) peer=10
2022-11-28T17:11:29Z GUI: ContractTablePriv::refreshWallet, cache size  10 MINE :  2
2022-11-28T17:11:29Z FeeEst: 1 > 60% decay 0.96200: feerate: -1 from (-1 - -1) 0.00% 0.0/(0.0 0 mem 0.0 out) Fail: (0 - 1e+99) 100.00% 0.8/(0.8 0 mem 0.0 out)
2022-11-28T17:11:29Z FeeEst: 2 > 85% decay 0.96200: feerate: -1 from (-1 - -1) 0.00% 0.0/(0.0 0 mem 0.0 out) Fail: (0 - 1e+99) 100.00% 0.8/(0.8 0 mem 0.0 out)
2022-11-28T17:11:29Z FeeEst: 4 > 95% decay 0.96200: feerate: -1 from (-1 - -1) 0.00% 0.0/(0.0 0 mem 0.0 out) Fail: (0 - 1e+99) 100.00% 0.8/(0.8 0 mem 0.0 out)
2022-11-28T17:11:29Z FeeEst: 4 > 95% decay 0.99520: feerate: -1 from (-1 - -1) 0.00% 0.0/(0.0 0 mem 0.0 out) Fail: (0 - 1e+99) 100.00% 1.0/(1.0 0 mem 0.0 out)
2022-11-28T17:11:29Z FeeEst: 4 > 95% decay 0.99931: feerate: -1 from (-1 - -1) 0.00% 0.0/(0.0 0 mem 0.0 out) Fail: (0 - 1e+99) 100.00% 1.0/(1.0 0 mem 0.0 out)
```

**Comment by BlockMechanic** [comment]
This should be resolved me thinks.

**Comment by defunctec** [comment]
Not quite, I still am unable to create an asset using GUI. 
More info, the Create button stops working once values are entered into the value fields. Until values are entered, the create button works.

**Comment by BlockMechanic** [comment]
I meant with the version i just released. Got delayed, sorry.

**Comment by defunctec** [comment]
Closing for now
