### ISSUE TITLE
daemon crashed with POTENTIAL DEADLOCK DETECTED

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#36]
```
2022-03-11T11:48:01Z POTENTIAL DEADLOCK DETECTED
2022-03-11T11:48:01Z Previous lock order was:
2022-03-11T11:48:01Z  'cs_mapMasternodePayeeVotes' in masternode/masternode-payments.cpp:478 (in thread 'crown-nodesync')
2022-03-11T11:48:01Z  (2) 'cs_mapMasternodeBlocks' in masternode/masternode-payments.cpp:478 (in thread 'crown-nodesync')
2022-03-11T11:48:01Z  (1) 'cs_main' in masternode/masternode-payments.cpp:482 (TRY) (in thread 'crown-nodesync')
2022-03-11T11:48:01Z Current lock order is:
2022-03-11T11:48:01Z  (1) 'cs_main' in miner.cpp:120 (in thread 'httpworker.0')
2022-03-11T11:48:01Z  'm_mempool.cs' in miner.cpp:120 (in thread 'httpworker.0')
2022-03-11T11:48:01Z  'pqueue->m_control_mutex' in ./checkqueue.h:218 (in thread 'httpworker.0')
2022-03-11T11:48:01Z  (2) 'cs_mapMasternodeBlocks' in masternode/masternode-payments.cpp:467 (in thread 'httpworker.0')
```

**Expected behavior**
daemon shouldn't crash

**Actual behavior**
daemon crashed unexpectedly, possibly while generating a block.

**To reproduce**
unknown

**System information**
5cb844b5c19adf72ba3f69b09524d82f9f0bfb9a self-build with debug symbols on Ubuntu 20.04

**debug.log**
```
2022-03-11T11:47:58Z Unknown inv type "mn announce 7de940739574acf700981be027d3799f7d8fc31d28fc4eb8e26907ece1c8cfcd" received from peer=13
2022-03-11T11:48:01Z Received a POST request for / from 127.0.0.1:33854
2022-03-11T11:48:01Z ThreadRPCServer method=generatetoaddress user=Library
2022-03-11T11:48:01Z COMMIT POSE -1
2022-03-11T11:48:01Z CreateNewBlock(): block weight: 1080 txs: 0 fees: 0 sigops 400
 CBlock(hash=27f496c22f58384ac723627d3c5830bfe25a24a14043fa6f87babda074a0d45a, ver=0x00000000, hashPrevBlock=0000000000000000000000000000000000000000000000000000000000000000, hashMerkleRoot=0000000000000000000000000000000000000000000000000000000000000000, nTime=1646999281, nBits=00000000, nNonce=0, vtx=1)
  CTransaction(hash=b884ff5255, ver=4, type=0, vin.size=1, vout.size=1, nLockTime=0, extraPayload.size=0)
CTxIn(COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295), coinbase 02d60600)
    CTxOutAsset
Name : Crown
Symbol : CRW
CAssetID : 1892dd304d6cf4e2f40d2bf465e8d47a48c240d375efac65f86a680c9706e401
Contract Hash : 0000000000000000000000000000000000000000000000000000000000000000 
Details (ver=1, transferable=yes, convertable=yes, limited=no, restricted=no, stakable=yes, infatable=no, type=1, expiry=0)

(nValue=100.00000000, scriptPubKey=OP_DUP OP_HASH160 baa8463136ded8d34327bdd140fbb1f7dac27a74 OP_EQUALVERIFY OP_CHECKSIG)



2022-03-11T11:48:01Z     - Sanity checks: 0.01ms [0.00s (0.01ms/blk)]
2022-03-11T11:48:01Z     - Fork checks: 0.06ms [0.00s (0.03ms/blk)]
2022-03-11T11:48:01Z       - Connect 1 transactions: 0.04ms (0.035ms/tx, 0.000ms/txin) [0.00s (0.06ms/blk)]
2022-03-11T11:48:01Z POTENTIAL DEADLOCK DETECTED
2022-03-11T11:48:01Z Previous lock order was:
2022-03-11T11:48:01Z  'cs_mapMasternodePayeeVotes' in masternode/masternode-payments.cpp:478 (in thread 'crown-nodesync')
2022-03-11T11:48:01Z  (2) 'cs_mapMasternodeBlocks' in masternode/masternode-payments.cpp:478 (in thread 'crown-nodesync')
2022-03-11T11:48:01Z  (1) 'cs_main' in masternode/masternode-payments.cpp:482 (TRY) (in thread 'crown-nodesync')
2022-03-11T11:48:01Z Current lock order is:
2022-03-11T11:48:01Z  (1) 'cs_main' in miner.cpp:120 (in thread 'httpworker.0')
2022-03-11T11:48:01Z  'm_mempool.cs' in miner.cpp:120 (in thread 'httpworker.0')
2022-03-11T11:48:01Z  'pqueue->m_control_mutex' in ./checkqueue.h:218 (in thread 'httpworker.0')
2022-03-11T11:48:01Z  (2) 'cs_mapMasternodeBlocks' in masternode/masternode-payments.cpp:467 (in thread 'httpworker.0')
```

**Backtrace**
Core was generated by `crownd'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f7745f5e700 (LWP 1822105))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f7749bb1859 in __GI_abort () at abort.c:79
#2  0x000055ecc10c8c74 in potential_deadlock_detected (mismatch={...}, 
    mismatch={...}, s2=std::vector of length 4, capacity 4 = {...}, s1=...)
    at sync.cpp:133
#3  push_lock (locklocation=..., c=<optimized out>) at sync.cpp:157
#4  EnterCritical (pszName=<optimized out>, pszFile=<optimized out>, 
    nLine=<optimized out>, cs=<optimized out>, fTry=fTry@entry=false)
    at sync.cpp:180
#5  0x000055ecc11246ce in UniqueLock<AnnotatedMixin<std::recursive_mutex>, std::unique_lock<std::recursive_mutex> >::Enter (nLine=<optimized out>, 
    pszFile=<optimized out>, pszName=<optimized out>, this=0x7f7745f58e60)
    at ./sync.h:136
#6  UniqueLock<AnnotatedMixin<std::recursive_mutex>, std::unique_lock<std::recursive_mutex> >::UniqueLock (this=0x7f7745f58e60, mutexIn=..., 
    pszName=<optimized out>, pszFile=<optimized out>, nLine=<optimized out>, 
    fTry=<optimized out>) at ./sync.h:164
#7  0x000055ecc1161636 in CMasternodePayments::IsTransactionValid (
    this=0x55ecc1ccdf00 <masternodePayments>, 
    nValueCreated=@0x7f7745f59380: 0, txNew=..., nBlockHeight=<optimized out>)
    at masternode/masternode-payments.cpp:467
#8  0x000055ecc11617a2 in IsBlockPayeeValid (
    nAmountCreated=@0x7f7745f59380: 0, txNew=..., 
    nBlockHeight=nBlockHeight@entry=1749, nTime=@0x7f773c001364: 1646999281, 
    nTimePrevBlock=@0x7f773c007010: 1646999221)
    at masternode/masternode-payments.cpp:105
#9  0x000055ecc138d533 in CChainState::ConnectBlock (this=<optimized out>, 
    block=..., state=..., pindex=<optimized out>, view=..., chainparams=..., 
    fJustCheck=<optimized out>)
    at /usr/include/c++/8/bits/shared_ptr_base.h:1018
#10 0x000055ecc13921c7 in TestBlockValidity (state=..., chainparams=..., 
    block=..., pindexPrev=pindexPrev@entry=0x7f773c006f70, 
    fCheckPOW=fCheckPOW@entry=false, 
    fCheckMerkleRoot=fCheckMerkleRoot@entry=false) at validation.cpp:4568
#11 0x000055ecc146fb11 in BlockAssembler::CreateNewBlock (
    this=this@entry=0x7f7745f5cae0, scriptPubKeyIn=...) at miner.cpp:186
#12 0x000055ecc1280fe9 in generateBlocks (chainman=..., mempool=..., 
    coinbase_script=..., nGenerate=<optimized out>, nMaxTries=<optimized out>)
    at rpc/mining.cpp:153
#13 0x000055ecc128179f in <lambda(const RPCHelpMan&, const JSONRPCRequest&)>::operator() (__closure=<optimized out>, self=..., request=...)
    at rpc/mining.cpp:289
#14 std::_Function_handler<UniValue(const RPCHelpMan&, const JSONRPCRequest&), g--Type <RET> for more, q to quit, c to continue without paging--
eneratetoaddress()::<lambda(const RPCHelpMan&, const JSONRPCRequest&)> >::_M_invoke(const std::_Any_data &, const RPCHelpMan &, const JSONRPCRequest &) (
    __functor=..., __args#0=..., __args#1=...)
    at /usr/include/c++/8/bits/std_function.h:283
#15 0x000055ecc124ba5f in std::function<UniValue (RPCHelpMan const&, JSONRPCRequest const&)>::operator()(RPCHelpMan const&, JSONRPCRequest const&) const (
    __args#1=..., __args#0=..., this=0x7f7745f5cdf0)
    at /usr/include/c++/8/bits/std_function.h:682
#16 RPCHelpMan::HandleRequest (request=..., this=0x7f7745f5cdd0)
    at ./rpc/util.h:342
#17 CRPCCommand::CRPCCommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, RPCHelpMan (*)(), std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)::{lambda(JSONRPCRequest const&, UniValue&, bool)#1}::operator()(JSONRPCRequest const&, UniValue&, bool) const (__closure=<optimized out>, request=..., 
    result=...) at ./rpc/server.h:111
#18 0x000055ecc12f7353 in std::function<bool (JSONRPCRequest const&, UniValue&, bool)>::operator()(JSONRPCRequest const&, UniValue&, bool) const (
    __args#2=<optimized out>, __args#1=..., __args#0=..., 
    this=0x55ecc1cd1520 <RegisterMiningRPCCommands(CRPCTable&)::commands+832>)
    at /usr/include/c++/8/bits/std_function.h:682
#19 ExecuteCommand (last_handler=true, result=..., request=..., command=...)
    at rpc/server.cpp:466
#20 CRPCTable::execute (this=<optimized out>, request=...)
    at rpc/server.cpp:449
#21 0x000055ecc143d761 in HTTPReq_JSONRPC (context=..., req=0x7f77240041c0)
    at httprpc.cpp:207
#22 0x000055ecc143f4e9 in std::function<bool (HTTPRequest*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::operator()(HTTPRequest*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (__args#1="", __args#0=<optimized out>, 
    this=0x7f7724002320) at /usr/include/c++/8/bits/std_function.h:682
#23 HTTPWorkItem::operator() (this=0x7f77240022f0) at httpserver.cpp:56
#24 WorkQueue<HTTPClosure>::Run (this=0x55ecc35bb760) at httpserver.cpp:115
#25 HTTPWorkQueueRun (queue=0x55ecc35bb760, worker_num=<optimized out>)
    at httpserver.cpp:343
#26 0x00007f7749fc3de4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#27 0x00007f774a0fd609 in start_thread (arg=<optimized out>)
    at pthread_create.c:477
#28 0x00007f7749cae163 in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by walkjivefly** [comment]
Crash happens on both regular wallet and MN daemon.

**Comment by walkjivefly** [comment]
Still crashes with 2e05a2cd7b64d9a3273361da277c77b4d28818b6 but not as frequently.

**debug.log**
```
2022-03-11T21:15:57Z CSystemnodeSync::GetNextAsset - Sync has finished
2022-03-11T21:16:01Z tor: Error connecting to Tor control socket
2022-03-11T21:16:01Z tor: Not connected to Tor control port 127.0.0.1:9051, trying to reconnect
2022-03-11T21:16:01Z received: inv (37 bytes) peer=10
2022-03-11T21:16:01Z sending getdata (37 bytes) peer=10
2022-03-11T21:16:01Z received: block (271 bytes) peer=10
2022-03-11T21:16:01Z received block 0000d41eec13f338f5ece08f293f1af66ece1fd599c8034dec9a9e96f0315716 peer=10
2022-03-11T21:16:01Z NewPoWValidBlock: block hash=0000d41eec13f338f5ece08f293f1af66ece1fd599c8034dec9a9e96f0315716
2022-03-11T21:16:01Z   - Load block from disk: 0.00ms [0.00s]
2022-03-11T21:16:01Z     - Sanity checks: 0.00ms [0.00s (0.00ms/blk)]
2022-03-11T21:16:01Z     - Fork checks: 0.08ms [0.00s (0.04ms/blk)]
2022-03-11T21:16:01Z       - Connect 1 transactions: 0.07ms (0.075ms/tx, 0.000ms/txin) [0.00s (0.03ms/blk)]
2022-03-11T21:16:01Z Client not synced, skipping block payee checks
2022-03-11T21:16:01Z POTENTIAL DEADLOCK DETECTED
2022-03-11T21:16:01Z Previous lock order was:
2022-03-11T21:16:01Z  'cs_mapSystemnodePayeeVotes' in systemnode/systemnode-payments.cpp:343 (in thread 'crown-nodesync')
2022-03-11T21:16:01Z  (2) 'cs_mapSystemnodeBlocks' in systemnode/systemnode-payments.cpp:343 (in thread 'crown-nodesync')
2022-03-11T21:16:01Z  (1) 'cs_main' in systemnode/systemnode-payments.cpp:347 (TRY) (in thread 'crown-nodesync')
2022-03-11T21:16:01Z Current lock order is:
2022-03-11T21:16:01Z  'm_cs_chainstate' in validation.cpp:3487 (in thread 'msghand')
2022-03-11T21:16:01Z  (1) 'cs_main' in validation.cpp:3502 (in thread 'msghand')
2022-03-11T21:16:01Z  'm_mempool.cs' in validation.cpp:3503 (in thread 'msghand')
2022-03-11T21:16:01Z  'pqueue->m_control_mutex' in ./checkqueue.h:218 (in thread 'msghand')
2022-03-11T21:16:01Z  (2) 'cs_mapSystemnodeBlocks' in systemnode/systemnode-payments.cpp:76 (in thread 'msghand')
``` 
**backtrace**
```
Core was generated by `crownd'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7feedd7fa700 (LWP 1839833))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fef086a3859 in __GI_abort () at abort.c:79
#2  0x000055f8876aacce in potential_deadlock_detected (mismatch={...}, mismatch={...}, s2=std::vector of length 5, capacity 5 = {...}, s1=...) at sync.cpp:133
#3  push_lock (locklocation=..., c=<optimized out>) at sync.cpp:157
#4  EnterCritical (pszName=<optimized out>, pszFile=<optimized out>, nLine=<optimized out>, cs=<optimized out>, fTry=fTry@entry=false) at sync.cpp:180
#5  0x000055f88770683e in UniqueLock<AnnotatedMixin<std::recursive_mutex>, std::unique_lock<std::recursive_mutex> >::Enter (nLine=<optimized out>, pszFile=<optimized out>, 
    pszName=<optimized out>, this=0x7feedd7f1480) at ./sync.h:136
#6  UniqueLock<AnnotatedMixin<std::recursive_mutex>, std::unique_lock<std::recursive_mutex> >::UniqueLock (this=0x7feedd7f1480, mutexIn=..., pszName=<optimized out>, 
    pszFile=<optimized out>, nLine=<optimized out>, fTry=<optimized out>) at ./sync.h:164
#7  0x000055f887900576 in CSystemnodePayments::IsTransactionValid (this=0x55f8882b6ba0 <systemnodePayments>, nValueCreated=@0x7feedd7f19a0: 0, txNew=..., 
    nBlockHeight=<optimized out>) at systemnode/systemnode-payments.cpp:76
#8  0x000055f8879006e2 in SNIsBlockPayeeValid (nValueCreated=@0x7feedd7f19a0: 0, txNew=..., nBlockHeight=nBlockHeight@entry=2102, nTime=@0x7feec4009e84: 1647033361, 
    nTimePrevBlock=@0x7feec401be50: 1647033241) at systemnode/systemnode-payments.cpp:55
#9  0x000055f88796f655 in CChainState::ConnectBlock (this=<optimized out>, block=..., state=..., pindex=<optimized out>, view=..., chainparams=..., fJustCheck=<optimized out>)
    at /usr/include/c++/8/bits/shared_ptr_base.h:1018
#10 0x000055f887973161 in CChainState::ConnectTip (this=0x55f88986fd20, state=..., chainparams=..., pindexNew=0x7feec404fb70, pblock=..., connectTrace=..., disconnectpool=...)
    at validation.cpp:3238
#11 0x000055f88797906a in CChainState::ActivateBestChainStep (this=0x55f88986fd20, state=..., chainparams=..., pindexMostWork=0x7feec404fb70, 
    pblock=std::shared_ptr<const class CBlock> (use count 6, weak count 0) = {...}, fInvalidFound=@0x7feedd7f4a5f: false, connectTrace=...)
    at /usr/include/c++/8/bits/shared_ptr_base.h:614
#12 0x000055f887979d20 in CChainState::ActivateBestChain (this=<optimized out>, state=..., chainparams=..., 
    pblock=std::shared_ptr<const class CBlock> (use count 6, weak count 0) = {...}) at ./uint256.h:49
#13 0x000055f88797aace in ChainstateManager::ProcessNewBlock (this=this@entry=0x55f8882b74c0 <g_chainman>, chainparams=..., 
--Type <RET> for more, q to quit, c to continue without paging--
    eak count 0) = {...}, fForceProcessing=fForceProcessing@entry=true, fNewBlock=fNewBlock@entry=0x7feedd7f4d65)
    at /usr/include/c++/8/ext/atomicity.h:96
#14 0x000055f88778e68d in PeerManager::ProcessMessage (this=0x55f88988f4f0, pfrom=..., msg_type=..., vRecv=..., time_received=..., interruptMsgProc=...)
    at /usr/include/c++/8/bits/shared_ptr.h:246
#15 0x000055f887791071 in PeerManager::ProcessMessages (this=0x55f88988f4f0, pfrom=0x7feed425b730, interruptMsgProc=...) at net_processing.cpp:3950
#16 0x000055f887752a2a in CConnman::ThreadMessageHandler (this=0x55f889897250) at net.cpp:2287
#17 0x000055f8876e0618 in std::function<void ()>::operator()() const (this=0x7feedd7f9e50) at /usr/include/c++/8/bits/std_function.h:682
#18 TraceThread<std::function<void ()> >(char const*, std::function<void ()>) (name=<optimized out>, func=...) at ./util/system.h:455
#19 0x000055f8877673ff in std::__invoke_impl<void, void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> >(std::__invoke_other, void (*&&)(char const*, std::function<void ()>), char const*&&, std::function<void ()>&&) (__f=<optimized out>) at /usr/include/c++/8/bits/move.h:182
#20 std::__invoke<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> >(void (*&&)(char const*, std::function<void ()>), char const*&&, std::function<void ()>&&) (__fn=<optimized out>) at /usr/include/c++/8/bits/invoke.h:95
#21 std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> > >::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>) (this=<optimized out>) at /usr/include/c++/8/thread:244
#22 std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> > >::operator()() (this=<optimized out>)
    at /usr/include/c++/8/thread:253
#23 std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> > > >::_M_run() (
    this=<optimized out>) at /usr/include/c++/8/thread:196
#24 0x00007fef08ab5de4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#25 0x00007fef08bef609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#26 0x00007fef087a0163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by walkjivefly** [comment]
Still crashing regularly with 0.0.0.17 self-compiled without debug options.
debug.log says
```
...
2022-03-21T09:33:48Z CMasternodeSync::GetNextAsset - Sync has finished
2022-03-21T09:34:33Z POTENTIAL DEADLOCK DETECTED
2022-03-21T09:34:33Z Previous lock order was:
2022-03-21T09:34:33Z  'cs_mapMasternodePayeeVotes' in masternode/masternode-payments.cpp:477 (in thread 'crown-nodesync')
2022-03-21T09:34:33Z  (2) 'cs_mapMasternodeBlocks' in masternode/masternode-payments.cpp:477 (in thread 'crown-nodesync')
2022-03-21T09:34:33Z  (1) 'cs_main' in masternode/masternode-payments.cpp:481 (TRY) (in thread 'crown-nodesync')
2022-03-21T09:34:33Z Current lock order is:
2022-03-21T09:34:33Z  'm_cs_chainstate' in validation.cpp:3487 (in thread 'msghand')
2022-03-21T09:34:33Z  (1) 'cs_main' in validation.cpp:3502 (in thread 'msghand')
2022-03-21T09:34:33Z  'm_mempool.cs' in validation.cpp:3503 (in thread 'msghand')
2022-03-21T09:34:33Z  'pqueue->m_control_mutex' in ./checkqueue.h:218 (in thread 'msghand')
2022-03-21T09:34:33Z  (2) 'cs_mapMasternodeBlocks' in masternode/masternode-payments.cpp:466 (in thread 'msghand')
```

and core has
```
Core was generated by `/home/mark/.crowntest/bin/crownd -testnet -datadir=/home/mark/.crowntest'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fe385fd47bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
[Current thread is 1 (Thread 0x7fe346ffd700 (LWP 29123))]
(gdb) bt
#0  0x00007fe385fd47bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fe385fbf535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x000056144502c996 in potential_deadlock_detected (mismatch={...}, 
    mismatch={...}, s2=std::vector of length 5, capacity 5 = {...}, s1=...)
    at sync.cpp:133
#3  push_lock (locklocation=..., c=<optimized out>) at sync.cpp:157
#4  EnterCritical (pszName=<optimized out>, pszFile=<optimized out>, 
    nLine=<optimized out>, cs=<optimized out>, fTry=fTry@entry=false)
    at sync.cpp:180
#5  0x000056144508845e in UniqueLock<AnnotatedMixin<std::recursive_mutex>, std::unique_lock<std::recursive_mutex> >::Enter (nLine=<optimized out>, 
    pszFile=<optimized out>, pszName=<optimized out>, this=0x7fe346ff46f0)
    at ./sync.h:136
#6  UniqueLock<AnnotatedMixin<std::recursive_mutex>, std::unique_lock<std::recursive_mutex> >::UniqueLock (this=0x7fe346ff46f0, mutexIn=..., 
    pszName=<optimized out>, pszFile=<optimized out>, nLine=<optimized out>, 
    fTry=<optimized out>) at ./sync.h:164
#7  0x00005614450c3e16 in CMasternodePayments::IsTransactionValid (
    this=0x561445c30f00 <masternodePayments>, 
    nValueCreated=@0x7fe346ff4c10: 0, txNew=..., nBlockHeight=<optimized out>)
    at masternode/masternode-payments.cpp:466
#8  0x00005614450c3f82 in IsBlockPayeeValid (
    nAmountCreated=@0x7fe346ff4c10: 0, txNew=..., 
    nBlockHeight=nBlockHeight@entry=6694, nTime=@0x7fe34c043194: 1647855272, 
    nTimePrevBlock=@0x7fe32c04e700: 1647854972)
    at masternode/masternode-payments.cpp:105
#9  0x00005614452f1bc3 in CChainState::ConnectBlock (this=<optimized out>, 
    block=..., state=..., pindex=<optimized out>, view=..., chainparams=..., 
    fJustCheck=<optimized out>)
    at /usr/include/c++/8/bits/shared_ptr_base.h:1018
#10 0x00005614452f57c1 in CChainState::ConnectTip (this=0x561446cacbe0, 
    state=..., chainparams=..., pindexNew=0x7fe34c054180, pblock=..., 
    connectTrace=..., disconnectpool=...) at validation.cpp:3238
#11 0x00005614452fb6ca in CChainState::ActivateBestChainStep (
    this=0x561446cacbe0, state=..., chainparams=..., 
    pindexMostWork=0x7fe34c054180, 
    pblock=std::shared_ptr<const CBlock> (use count 6, weak count 0) = {...}, 
    fInvalidFound=@0x7fe346ff7ccf: false, connectTrace=...)
    at /usr/include/c++/8/bits/shared_ptr_base.h:614
#12 0x00005614452fc380 in CChainState::ActivateBestChain (
    this=<optimized out>, state=..., chainparams=..., 
    pblock=std::shared_ptr<const CBlock> (use count 6, weak count 0) = {...})
    at ./uint256.h:49
#13 0x00005614452fd12e in ChainstateManager::ProcessNewBlock (
    this=this@entry=0x561445c374c0 <g_chainman>, chainparams=..., 
    pblock=std::shared_ptr<const CBlock> (use count 6, weak count 0) = {...}, 
    fForceProcessing=fForceProcessing@entry=true, 
    fNewBlock=fNewBlock@entry=0x7fe346ff7fd5)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/include/c++/8/ext/atomicity.h:96
#14 0x0000561445110bd8 in PeerManager::ProcessMessage (this=0x561448303cf0, 
    pfrom=..., msg_type=..., vRecv=..., time_received=..., 
    interruptMsgProc=...) at /usr/include/c++/8/bits/shared_ptr.h:246
#15 0x0000561445113d21 in PeerManager::ProcessMessages (this=0x561448303cf0, 
    pfrom=0x7fe338258ea0, interruptMsgProc=...) at net_processing.cpp:3958
#16 0x00005614450d4d9a in CConnman::ThreadMessageHandler (this=0x561446d454c0)
    at net.cpp:2287
#17 0x0000561445062238 in std::function<void ()>::operator()() const (
    this=0x7fe346ffce50) at /usr/include/c++/8/bits/std_function.h:682
#18 TraceThread<std::function<void ()> >(char const*, std::function<void ()>) (
    name=<optimized out>, func=...) at ./util/system.h:455
#19 0x00005614450e9aaf in std::__invoke_impl<void, void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> >(std::__invoke_other, void (*&&)(char const*, std::function<void ()>), char const*&&, std::function<void ()>&&) (__f=<optimized out>) at /usr/include/c++/8/bits/move.h:182
#20 std::__invoke<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> >(void (*&&)(char const*, std::function<void ()>), char const*&&, std::function<void ()>&&) (__fn=<optimized out>)
    at /usr/include/c++/8/bits/invoke.h:95
#21 std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> > >::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>) (this=<optimized out>) at /usr/include/c++/8/thread:244
#22 std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> > >::operator()() (
    this=<optimized out>) at /usr/include/c++/8/thread:253
#23 std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> > > >::_M_run() (this=<optimized out>) at /usr/include/c++/8/thread:196
#24 0x00007fe3863b8b2f in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#25 0x00007fe3866b0fa3 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#26 0x00007fe3860964cf in clone () from /lib/x86_64-linux-gnu/libc.so.6
```
