### ISSUE TITLE
daemon crashed with POTENTIAL DEADLOCK DETECTED while doing something MN payment sync related

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#37]
daemon crashed unexpectedly with debug.log saying
```
2022-03-11T12:28:01Z received block 0000276d065b449abc55b615e70341de5a977b67c4dcf52fc1d6d0babfef5fe3 peer=21
2022-03-11T12:28:01Z NewPoWValidBlock: block hash=0000276d065b449abc55b615e70341de5a977b67c4dcf52fc1d6d0babfef5fe3
2022-03-11T12:28:01Z CMasternodePayments::ProcessBlock - Unknown Masternode
2022-03-11T12:28:01Z CBudgetManager::SubmitBudgetDraft - Found No Proposals For Period
2022-03-11T12:28:01Z   - Load block from disk: 0.00ms [0.00s]
2022-03-11T12:28:01Z     - Sanity checks: 0.00ms [0.00s (0.01ms/blk)]
2022-03-11T12:28:01Z     - Fork checks: 0.07ms [0.00s (0.03ms/blk)]
2022-03-11T12:28:01Z       - Connect 1 transactions: 0.05ms (0.048ms/tx, 0.000ms/txin) [0.00s (0.03ms/blk)]
2022-03-11T12:28:01Z POTENTIAL DEADLOCK DETECTED
2022-03-11T12:28:01Z Previous lock order was:
2022-03-11T12:28:01Z  'cs_mapMasternodePayeeVotes' in masternode/masternode-payments.cpp:478 (in thread 'crown-nodesync')
2022-03-11T12:28:01Z  (2) 'cs_mapMasternodeBlocks' in masternode/masternode-payments.cpp:478 (in thread 'crown-nodesync')
2022-03-11T12:28:01Z  (1) 'cs_main' in masternode/masternode-payments.cpp:482 (TRY) (in thread 'crown-nodesync')
2022-03-11T12:28:01Z Current lock order is:
2022-03-11T12:28:01Z  'm_cs_chainstate' in validation.cpp:3487 (in thread 'msghand')
2022-03-11T12:28:01Z  (1) 'cs_main' in validation.cpp:3502 (in thread 'msghand')
2022-03-11T12:28:01Z  'm_mempool.cs' in validation.cpp:3503 (in thread 'msghand')
2022-03-11T12:28:01Z  'pqueue->m_control_mutex' in ./checkqueue.h:218 (in thread 'msghand')
2022-03-11T12:28:01Z  (2) 'cs_mapMasternodeBlocks' in masternode/masternode-payments.cpp:467 (in thread 'msghand')
```

**Expected behavior**
daemon shouldn't crash

**To reproduce**
unknown

**System information**
5cb844b5c19adf72ba3f69b09524d82f9f0bfb9a self-build with debug symbols on Ubuntu 20.04

**backtrace**
```
Core was generated by `crownd'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f5389ffb700 (LWP 753487))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f53b4b06859 in __GI_abort () at abort.c:79
#2  0x0000560ac03d1c74 in potential_deadlock_detected (mismatch={...}, 
    mismatch={...}, s2=std::vector of length 5, capacity 5 = {...}, s1=...)
    at sync.cpp:133
#3  push_lock (locklocation=..., c=<optimized out>) at sync.cpp:157
#4  EnterCritical (pszName=<optimized out>, pszFile=<optimized out>, 
    nLine=<optimized out>, cs=<optimized out>, fTry=fTry@entry=false)
    at sync.cpp:180
#5  0x0000560ac042d6ce in UniqueLock<AnnotatedMixin<std::recursive_mutex>, std::unique_lock<std::recursive_mutex> >::Enter (nLine=<optimized out>, 
    pszFile=<optimized out>, pszName=<optimized out>, this=0x7f5389ff2450)
    at ./sync.h:136
#6  UniqueLock<AnnotatedMixin<std::recursive_mutex>, std::unique_lock<std::recursive_mutex> >::UniqueLock (this=0x7f5389ff2450, mutexIn=..., 
    pszName=<optimized out>, pszFile=<optimized out>, nLine=<optimized out>, 
    fTry=<optimized out>) at ./sync.h:164
#7  0x0000560ac046a636 in CMasternodePayments::IsTransactionValid (
    this=0x560ac0fd6f00 <masternodePayments>, 
    nValueCreated=@0x7f5389ff2970: 0, txNew=..., nBlockHeight=<optimized out>)
    at masternode/masternode-payments.cpp:467
#8  0x0000560ac046a7a2 in IsBlockPayeeValid (
    nAmountCreated=@0x7f5389ff2970: 0, txNew=..., 
    nBlockHeight=nBlockHeight@entry=1786, nTime=@0x7f5378009994: 1647001681, 
    nTimePrevBlock=@0x7f5378039a70: 1647001621)
    at masternode/masternode-payments.cpp:105
#9  0x0000560ac0696533 in CChainState::ConnectBlock (this=<optimized out>, 
    block=..., state=..., pindex=<optimized out>, view=..., chainparams=..., 
    fJustCheck=<optimized out>)
    at /usr/include/c++/8/bits/shared_ptr_base.h:1018
#10 0x0000560ac069a131 in CChainState::ConnectTip (this=0x560ac283bf20, 
    state=..., chainparams=..., pindexNew=0x7f537805b9b0, pblock=..., 
    connectTrace=..., disconnectpool=...) at validation.cpp:3238
#11 0x0000560ac06a003a in CChainState::ActivateBestChainStep (
    this=0x560ac283bf20, state=..., chainparams=..., 
    pindexMostWork=0x7f537805b9b0, 
    pblock=std::shared_ptr<const class CBlock> (use count 6, weak count 0) = {...}, fInvalidFound=@0x7f5389ff5a2f: false, connectTrace=...)
    at /usr/include/c++/8/bits/shared_ptr_base.h:614
#12 0x0000560ac06a0cf0 in CChainState::ActivateBestChain (
    this=<optimized out>, state=..., chainparams=..., 
    pblock=std::shared_ptr<const class CBlock> (use count 6, weak count 0) = {...}) at ./uint256.h:49
#13 0x0000560ac06a1a9e in ChainstateManager::ProcessNewBlock (
    this=this@entry=0x560ac0fdd4c0 <g_chainman>, chainparams=..., 
    pblock=std::shared_ptr<const class CBlock> (use count 6, weak count 0) = {...}, fForceProcessing=fForceProcessing@entry=true, 
    fNewBlock=fNewBlock@entry=0x7f5389ff5d3d)
    at /usr/include/c++/8/ext/atomicity.h:96
#14 0x0000560ac04b5609 in PeerManager::ProcessMessage (this=0x560ac2844c60, 
    pfrom=..., msg_type=..., vRecv=..., time_received=..., 
    interruptMsgProc=...) at /usr/include/c++/8/bits/shared_ptr.h:246
#15 0x0000560ac04b8061 in PeerManager::ProcessMessages (this=0x560ac2844c60, 
--Type <RET> for more, q to quit, c to continue without paging--
    pfrom=0x7f53844b3230, interruptMsgProc=...) at net_processing.cpp:3950
#16 0x0000560ac04798ca in CConnman::ThreadMessageHandler (this=0x560ac2955dc0)
    at net.cpp:2287
#17 0x0000560ac04074a8 in std::function<void ()>::operator()() const (
    this=0x7f5389ffae50) at /usr/include/c++/8/bits/std_function.h:682
#18 TraceThread<std::function<void ()> >(char const*, std::function<void ()>) (
    name=<optimized out>, func=...) at ./util/system.h:455
#19 0x0000560ac048e29f in std::__invoke_impl<void, void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> >(std::__invoke_other, void (*&&)(char const*, std::function<void ()>), char const*&&, std::function<void ()>&&) (__f=<optimized out>) at /usr/include/c++/8/bits/move.h:182
#20 std::__invoke<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> >(void (*&&)(char const*, std::function<void ()>), char const*&&, std::function<void ()>&&) (__fn=<optimized out>)
    at /usr/include/c++/8/bits/invoke.h:95
#21 std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> > >::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>) (this=<optimized out>) at /usr/include/c++/8/thread:244
#22 std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> > >::operator()() (
    this=<optimized out>) at /usr/include/c++/8/thread:253
#23 std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> > > >::_M_run() (this=<optimized out>) at /usr/include/c++/8/thread:196
#24 0x00007f53b4f18de4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#25 0x00007f53b5052609 in start_thread (arg=<optimized out>)
    at pthread_create.c:477
#26 0x00007f53b4c03163 in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**info threads**
```
(gdb) info threads
  Id   Target Id                          Frame 
* 1    Thread 0x7f5389ffb700 (LWP 753487) __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:50
  2    Thread 0x7f53b26b6700 (LWP 753472) futex_wait_cancelable (
    private=<optimized out>, expected=0, 
    futex_word=0x560ac0fddd70 <scriptcheckqueue+80>)
    at ../sysdeps/nptl/futex-internal.h:183
  3    Thread 0x7f53b4ae2bc0 (LWP 753471) 0x00007f53b4bc126f in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, 
    req=req@entry=0x7ffd6f486fc0, rem=rem@entry=0x7ffd6f486fc0)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  4    Thread 0x7f53b16b4700 (LWP 753474) 0x00007f53b4c0349e in epoll_wait (
    epfd=5, events=0x560ac28447d0, maxevents=32, timeout=-1)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  5    Thread 0x7f53b1eb5700 (LWP 753473) futex_abstimed_wait_cancelable (
    private=<optimized out>, abstime=0x7f53b1eb4d60, clockid=<optimized out>, 
    expected=0, futex_word=0x560ac27de8ec)
    at ../sysdeps/nptl/futex-internal.h:320
  6    Thread 0x7f538affd700 (LWP 753485) futex_abstimed_wait_cancelable (
    private=<optimized out>, abstime=0x7f538affca20, clockid=<optimized out>, 
    expected=0, futex_word=0x560ac29a62f0)
    at ../sysdeps/nptl/futex-internal.h:320
  7    Thread 0x7f538b7fe700 (LWP 753484) futex_abstimed_wait_cancelable (
    private=<optimized out>, abstime=0x7f538b7fdad0, clockid=<optimized out>, 
    expected=0, futex_word=0x560ac29a62f0)
    at ../sysdeps/nptl/futex-internal.h:320
  8    Thread 0x7f53b0eb3700 (LWP 753475) futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x560ac2835ec0)
    at ../sysdeps/nptl/futex-internal.h:183
  9    Thread 0x7f53a17fa700 (LWP 753481) 0x00007f53b4c0349e in epoll_wait (
    epfd=34, events=0x560ac4470fd0, maxevents=32, timeout=38443)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  10   Thread 0x7f53a3fff700 (LWP 753476) futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x560ac2835ec0)
    at ../sysdeps/nptl/futex-internal.h:183
  11   Thread 0x7f53a0ff9700 (LWP 753482) __lll_lock_wait (
    futex=futex@entry=0x560ac26a9468, private=0) at lowlevellock.c:52
  12   Thread 0x7f53a37fe700 (LWP 753477) futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x560ac2835ec0)
    at ../sysdeps/nptl/futex-internal.h:183
  13   Thread 0x7f53a2ffd700 (LWP 753478) futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x560ac2835ec0)
    at ../sysdeps/nptl/futex-internal.h:183
  14   Thread 0x7f538a7fc700 (LWP 753486) futex_abstimed_wait_cancelable (
    private=<optimized out>, abstime=0x7f538a7fb3d0, clockid=<optimized out>, 
    expected=0, futex_word=0x560ac29a62f0)
    at ../sysdeps/nptl/futex-internal.h:320
```

**Comment by walkjivefly** [comment]
Closed as dupe of https://github.com/Crowndev/crown/issues/36
so probably not related to the present/last crown-cli command issued.
