### ISSUE TITLE
SIGSEGV on startmasternode all

### ISSUE THREAD

**Issue by walkjivefly** [Crowndev/crown#41]
2e05a2cd7b64d9a3273361da277c77b4d28818b6 crownd crashes on `startmasternode all`

**Expected behavior**
`startmasternode` should not crash

**Actual behavior**
```
crown@crown-testnet-10:~/.crown/testnet3$ crown-cli startmasternode all false
error: Could not connect to the server 127.0.0.1:8451

Make sure the crownd server is running and that you are connecting to the correct RPC port.
```

**To reproduce**
as above.

**System information**
Self-built 2e05a2cd7b64d9a3273361da277c77b4d28818b6 with debug symbols on Ubuntu 20.04

**backtrace**
```
Core was generated by `crownd'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fd4dffff700 (LWP 1839311))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fd513783859 in __GI_abort () at abort.c:79
#2  0x0000556084b52745 in AssertLockHeldInternal<AnnotatedMixin<std::recursive_mutex> > (pszName=<optimized out>, 
    pszName@entry=0x556084eb5ceb "cs_mapMasternodeBlocks", 
    pszFile=<optimized out>, 
    pszFile@entry=0x556084eb5d90 "masternode/masternode-payments.cpp", 
    nLine=<optimized out>, nLine@entry=467, 
    cs=cs@entry=0x55608517b0a0 <cs_mapMasternodeBlocks>)
    at /usr/include/c++/8/ext/new_allocator.h:86
#3  0x0000556084611798 in CMasternodePayments::IsTransactionValid (
    this=this@entry=0x55608517ef00 <masternodePayments>, 
    nValueCreated=@0x7fd4dfff69a0: 0, txNew=..., nBlockHeight=<optimized out>, 
    nBlockHeight@entry=2094) at masternode/masternode-payments.cpp:467
#4  0x0000556084611902 in IsBlockPayeeValid (
    nAmountCreated=@0x7fd4dfff69a0: 0, txNew=..., 
    nBlockHeight=nBlockHeight@entry=2094, nTime=@0x7fd4d4009b34: 1647032401, 
    nTimePrevBlock=@0x7fd4d404d280: 1647032281)
    at masternode/masternode-payments.cpp:105
#5  0x000055608483d563 in CChainState::ConnectBlock (this=<optimized out>, 
    block=..., state=..., pindex=<optimized out>, view=..., chainparams=..., 
    fJustCheck=<optimized out>)
    at /usr/include/c++/8/bits/shared_ptr_base.h:1018
--Type <RET> for more, q to quit, c to continue without paging--
#6  0x0000556084841161 in CChainState::ConnectTip (this=0x556085ce1d20, 
    state=..., chainparams=..., pindexNew=0x7fd4d404f0f0, pblock=..., 
    connectTrace=..., disconnectpool=...) at validation.cpp:3238
#7  0x000055608484706a in CChainState::ActivateBestChainStep (
    this=0x556085ce1d20, state=..., chainparams=..., 
    pindexMostWork=0x7fd4d404f0f0, 
    pblock=std::shared_ptr<const class CBlock> (use count 6, weak count 0) = {...}, fInvalidFound=@0x7fd4dfff9a5f: false, connectTrace=...)
    at /usr/include/c++/8/bits/shared_ptr_base.h:614
#8  0x0000556084847d20 in CChainState::ActivateBestChain (
    this=<optimized out>, state=..., chainparams=..., 
    pblock=std::shared_ptr<const class CBlock> (use count 6, weak count 0) = {...}) at ./uint256.h:49
#9  0x0000556084848ace in ChainstateManager::ProcessNewBlock (
    this=this@entry=0x5560851854c0 <g_chainman>, chainparams=..., 
    pblock=std::shared_ptr<const class CBlock> (use count 6, weak count 0) = {...}, fForceProcessing=fForceProcessing@entry=true, 
    fNewBlock=fNewBlock@entry=0x7fd4dfff9d65)
    at /usr/include/c++/8/ext/atomicity.h:96
#10 0x000055608465c68d in PeerManager::ProcessMessage (this=0x556085d014f0, 
    pfrom=..., msg_type=..., vRecv=..., time_received=..., 
    interruptMsgProc=...) at /usr/include/c++/8/bits/shared_ptr.h:246
#11 0x000055608465f071 in PeerManager::ProcessMessages (this=0x556085d014f0, 
--Type <RET> for more, q to quit, c to continue without paging--
    pfrom=0x7fd4e025aaa0, interruptMsgProc=...) at net_processing.cpp:3950
#12 0x0000556084620a2a in CConnman::ThreadMessageHandler (this=0x556085d09250)
    at net.cpp:2287
#13 0x00005560845ae618 in std::function<void ()>::operator()() const (
    this=0x7fd4dfffee50) at /usr/include/c++/8/bits/std_function.h:682
#14 TraceThread<std::function<void ()> >(char const*, std::function<void ()>) (
    name=<optimized out>, func=...) at ./util/system.h:455
#15 0x00005560846353ff in std::__invoke_impl<void, void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> >(std::__invoke_other, void (*&&)(char const*, std::function<void ()>), char const*&&, std::function<void ()>&&) (__f=<optimized out>) at /usr/include/c++/8/bits/move.h:182
#16 std::__invoke<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> >(void (*&&)(char const*, std::function<void ()>), char const*&&, std::function<void ()>&&) (__fn=<optimized out>)
    at /usr/include/c++/8/bits/invoke.h:95
#17 std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> > >::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>) (this=<optimized out>) at /usr/include/c++/8/thread:244
#18 std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> > >::operator()() (
    this=<optimized out>) at /usr/include/c++/8/thread:253
#19 std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, std::function<void ()> > > >::_M_run()--Type <RET> for more, q to quit, c to continue without paging--
 (this=<optimized out>) at /usr/include/c++/8/thread:196
#20 0x00007fd513b95de4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#21 0x00007fd513ccf609 in start_thread (arg=<optimized out>)
    at pthread_create.c:477
#22 0x00007fd513880163 in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by walkjivefly** [comment]
However, when I tried again later, this happened:
```
crown@crown-testnet-10:~$ crown-cli startmasternode all false
{
  "overall": "Successfully started 0 masternodes, failed to start 3, total 3",
  "detail": [
    {
      "alias": "legacyMN",
      "result": "failed",
      "error": "Could not allocate txin b4cd5e37fd37202acb5153acd9d48cfe44f2d475a78936c835f4ecb46c3b788c:1 for masternode 92.60.46.27:18333"
    },
    {
      "alias": "segwitMN",
      "result": "failed",
      "error": "Could not allocate txin 28ebfd479cd84da3298f5d08277ad3333881604423cb6c1051ca12f455dcdfe0:1 for masternode 92.60.46.28:18333"
    },
    {
      "alias": "bech32MN",
      "result": "failed",
      "error": "Could not allocate txin d150845ba77666a14d493bed5d2d95ef46fb1b55d6f820fcd112295d0f52ad67:1 for masternode 92.60.46.29:18333"
    }
  ]
}
crown@crown-testnet-10:~$ crown-cli walletpassphrase xsn05 9999999999 false
crown@crown-testnet-10:~$ crown-cli startmasternode all false
{
  "overall": "Successfully started 3 masternodes, failed to start 0, total 3",
  "detail": [
    {
      "alias": "legacyMN",
      "result": "success",
      "error": ""
    },
    {
      "alias": "segwitMN",
      "result": "success",
      "error": ""
    },
    {
      "alias": "bech32MN",
      "result": "success",
      "error": ""
    }
  ]
}
```
but it fell over a few seconds later with debug.log showing 
```
022-03-11T21:42:01Z received: block (271 bytes) peer=12
2022-03-11T21:42:01Z received block 000016093a3565cc9ac35cd9d99b699ab11c67c5cc68e48cdb5bb114855fdb24 peer=12
2022-03-11T21:42:01Z NewPoWValidBlock: block hash=000016093a3565cc9ac35cd9d99b699ab11c67c5cc68e48cdb5bb114855fdb24
2022-03-11T21:42:01Z   - Load block from disk: 0.00ms [0.00s]
2022-03-11T21:42:01Z     - Sanity checks: 0.00ms [0.00s (0.01ms/blk)]
2022-03-11T21:42:01Z     - Fork checks: 0.10ms [0.00s (0.05ms/blk)]
2022-03-11T21:42:01Z       - Connect 1 transactions: 0.09ms (0.090ms/tx, 0.000ms/txin) [0.00s (0.03ms/blk)]
```
and a new backtrace.
